### ISSUE TITLE
crash in Cbc on miqcp

### ISSUE THREAD

**Issue by svigerske** [coin-or/SHOT#13]
On the problem
```
Variables  x1,x2,x3,b4,b5;
Binary Variables  b4,b5;
Equations  e1,e2,e3,e4;

e1.. -(sqr((-1.9) + x1) + sqr((-1.15) + x2)) + x3 =E= 0;
e2..    x1 + x2 - 2*b4 =L= 2.8;
e3..    x1 + x2 - 2*b4 =G= 1.2;
e4..    x1 - b5 =E= 1;

Model m / all /;
m.optcr      = 1E-6;
Solve m using MIQCP minimizing x3;
```
I get a segmentation fault of SHOT within CBC:
```
SHOT             31.0.0 re4be038 ALFA Released 19Dec19 LEG x86 64bit/Linux    

╶ Supporting Hyperplane Optimization Toolkit (SHOT) ──────────────────────────────────────────────────────────────────╴

  Andreas Lundell and Jan Kronqvist, Åbo Akademi University, Finland.
  See documentation for full list of contributors and utilized software libraries.

  Version: 1.0.alpha 1. Git hash: be1dabb. Released Jan 17 2020. 

  For more information visit https://shotsolver.dev

 Reading options from shot.opt

╶ Problem instance ───────────────────────────────────────────────────────────────────────────────────────────────────╴

                             Original             Reformulated

 Problem classification:     MIQP, convex         MIQP, convex
 Objective function type:    quadratic            quadratic

 Number of constraints:      3                    3
  - linear:                  3                    3

 Number of variables:        4                    4
  - real:                    2                    2
  - binary:                  2                    2


╶ Options ────────────────────────────────────────────────────────────────────────────────────────────────────────────╴

 No options file specified.

 Nondefault options used:

  - Dual.MIP.NumberOfThreads = 1
  - Dual.MIP.Solver = 2
  - Dual.TreeStrategy = 0
  - Model.Reformulation.Quadratics.Strategy = 0
  - Primal.Tolerance.TrustLinearConstraintValues = false
  - Subsolver.Ipopt.LinearSolver = 1
  - Termination.IterationLimit = 2147483647
  - Termination.ObjectiveGap.Absolute = 1e-10
  - Termination.ObjectiveGap.Relative = 1e-06
  - Termination.TimeLimit = 1000

  - solver:                  Cbc

 Primal NLP solver:          Ipopt with HSL MA27 linear solver


free(): invalid pointer

Program received signal SIGABRT, Aborted.
0x00007ffff7a89f25 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7a89f25 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7a73897 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7acd258 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff7ad477a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff7ad614c in _int_free () from /usr/lib/libc.so.6
#5  0x00007fffeff32c07 in ClpSimplexDual::dual(int, int) () from 
#6  0x00007fffeff0fbd9 in ClpSimplex::dual(int, int) () from 
#7  0x00007fffefe7c55f in OsiClpSolverInterface::resolve() () from 
#8  0x00007fffefd5276a in CbcModel::initialSolve() () from 
#9  0x00007fffefc8593d in CbcMain1(int, char const**, CbcModel&, int (*)(CbcModel*, int), CbcSolverUsefulData&) () from 
#10 0x00007fffefcb0655 in CbcMain1(int, char const**, CbcModel&) () from 
#11 0x00007fffef6f3447 in SHOT::MIPSolverCbc::solveProblem (this=0x55555565b8d0) at MIPSolverCbc.cpp:440
#12 0x00007fffef7622a2 in SHOT::TaskSolveIteration::run (this=0x55555568f6d0) at TaskSolveIteration.cpp:128
#13 0x00007fffef6d29f2 in SHOT::SolutionStrategyMultiTree::solveProblem (this=0x555555673ca0) at SolutionStrategyMultiTree.cpp:305
#14 0x00007fffef67084b in SHOT::Solver::solveProblem (this=0x7fffffffc840) at Solver.cpp:552
#15 0x00007fffef7df565 in shtCallSolver (Cptr=0x555555623530) at EntryPointsGAMS.cpp:201
#16 0x00007fffef7dfa64 in C__shtCallSolver (Cptr=0x555555623530) at EntryPointsGAMS.cpp:252
```

valgrind indicates that somethings has gone wrong earlier, though:
```

 Primal NLP solver:          Ipopt with HSL MA27 linear solver


Invalid read of size 1
   at 0x6046E67: CbcMain1(int, char const**, CbcModel&, int (*)(CbcModel*, int), CbcSolverUsefulData&) (in )
   by 0x6079654: CbcMain1(int, char const**, CbcModel&) (in )
   by 0x5ABC446: SHOT::MIPSolverCbc::solveProblem() (MIPSolverCbc.cpp:440)
   by 0x5B2B2A1: SHOT::TaskSolveIteration::run() (TaskSolveIteration.cpp:128)
   by 0x5A9B9F1: SHOT::SolutionStrategyMultiTree::solveProblem() (SolutionStrategyMultiTree.cpp:305)
   by 0x5A3984A: SHOT::Solver::solveProblem() (Solver.cpp:552)
   by 0x5BA8564: shtCallSolver (EntryPointsGAMS.cpp:201)
   by 0x5BA8A63: C__shtCallSolver (EntryPointsGAMS.cpp:252)
   by 0x52AFFEE: GMSCONF_tgmsconf_DOT_sccallsolver(GMSCONF_tgmsconf_OD_S*, int, void*, void*) (gmsconf.c:2443)
   by 0x52A4B6D: libsolver(unsigned char*, unsigned char*, unsigned char const*, GMOMDODEFEX_tgmomodel_OD_S**, GEVDOORG_tgmsenvironment_OD_S**) (gevdoorg.c:3042)
   by 0x52A61A3: GEVDOORG_tgmsenvironment_DOT_gevcallsolver(GEVDOORG_tgmsenvironment_OD_S*, void*, unsigned char const*, unsigned char const*, int, int, unsigned char const*, unsigned char const*, double, int, int, double, double, void**, unsigned char*) (gevdoorg.c:3427)
   by 0x5241786: gevcallsolver (joatdclib.c:5854)
 Address 0x5158ab0 is 0 bytes inside a block of size 31 free'd
   at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:586)
   by 0x5ABBBB2: SHOT::MIPSolverCbc::solveProblem() (MIPSolverCbc.cpp:390)
   by 0x5B2B2A1: SHOT::TaskSolveIteration::run() (TaskSolveIteration.cpp:128)
   by 0x5A9B9F1: SHOT::SolutionStrategyMultiTree::solveProblem() (SolutionStrategyMultiTree.cpp:305)
   by 0x5A3984A: SHOT::Solver::solveProblem() (Solver.cpp:552)
   by 0x5BA8564: shtCallSolver (EntryPointsGAMS.cpp:201)
   by 0x5BA8A63: C__shtCallSolver (EntryPointsGAMS.cpp:252)
   by 0x52AFFEE: GMSCONF_tgmsconf_DOT_sccallsolver(GMSCONF_tgmsconf_OD_S*, int, void*, void*) (gmsconf.c:2443)
   by 0x52A4B6D: libsolver(unsigned char*, unsigned char*, unsigned char const*, GMOMDODEFEX_tgmomodel_OD_S**, GEVDOORG_tgmsenvironment_OD_S**) (gevdoorg.c:3042)
   by 0x52A61A3: GEVDOORG_tgmsenvironment_DOT_gevcallsolver(GEVDOORG_tgmsenvironment_OD_S*, void*, unsigned char const*, unsigned char const*, int, int, unsigned char const*, unsigned char const*, double, int, int, double, double, void**, unsigned char*) (gevdoorg.c:3427)
   by 0x5241786: gevcallsolver (joatdclib.c:5854)
   by 0x11ECE9: GEVMDODEF_tgmsenvironment_DOT_gevcallsolver(GEVMDODEF_tgmsenvironment_OD_S*, void*, unsigned char const*, unsigned char const*, int, int, unsigned char const*, unsigned char const*, double, int, int, double, double, void**, unsigned char*) (gevmdodef.c:848)
 Block was alloc'd at
   at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:344)
   by 0x49D5631: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) (basic_string.tcc:317)
   by 0x49D6581: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long) (basic_string.tcc:466)
   by 0x59D7489: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) (basic_string.h:6111)
   by 0x5ABBB90: SHOT::MIPSolverCbc::solveProblem() (MIPSolverCbc.cpp:390)
   by 0x5B2B2A1: SHOT::TaskSolveIteration::run() (TaskSolveIteration.cpp:128)
   by 0x5A9B9F1: SHOT::SolutionStrategyMultiTree::solveProblem() (SolutionStrategyMultiTree.cpp:305)
   by 0x5A3984A: SHOT::Solver::solveProblem() (Solver.cpp:552)
   by 0x5BA8564: shtCallSolver (EntryPointsGAMS.cpp:201)
   by 0x5BA8A63: C__shtCallSolver (EntryPointsGAMS.cpp:252)
   by 0x52AFFEE: GMSCONF_tgmsconf_DOT_sccallsolver(GMSCONF_tgmsconf_OD_S*, int, void*, void*) (gmsconf.c:2443)
   by 0x52A4B6D: libsolver(unsigned char*, unsigned char*, unsigned char const*, GMOMDODEFEX_tgmomodel_OD_S**, GEVDOORG_tgmsenvironment_OD_S**) (gevdoorg.c:3042)

Invalid read of size 1
   at 0x6046E3B: CbcMain1(int, char const**, CbcModel&, int (*)(CbcModel*, int), CbcSolverUsefulData&) (in )
   by 0x6079654: CbcMain1(int, char const**, CbcModel&) (in )
   by 0x5ABC446: SHOT::MIPSolverCbc::solveProblem() (MIPSolverCbc.cpp:440)
   by 0x5B2B2A1: SHOT::TaskSolveIteration::run() (TaskSolveIteration.cpp:128)
   by 0x5A9B9F1: SHOT::SolutionStrategyMultiTree::solveProblem() (SolutionStrategyMultiTree.cpp:305)
   by 0x5A3984A: SHOT::Solver::solveProblem() (Solver.cpp:552)
   by 0x5BA8564: shtCallSolver (EntryPointsGAMS.cpp:201)
   by 0x5BA8A63: C__shtCallSolver (EntryPointsGAMS.cpp:252)
   by 0x52AFFEE: GMSCONF_tgmsconf_DOT_sccallsolver(GMSCONF_tgmsconf_OD_S*, int, void*, void*) (gmsconf.c:2443)
   by 0x52A4B6D: libsolver(unsigned char*, unsigned char*, unsigned char const*, GMOMDODEFEX_tgmomodel_OD_S**, GEVDOORG_tgmsenvironment_OD_S**) (gevdoorg.c:3042)
   by 0x52A61A3: GEVDOORG_tgmsenvironment_DOT_gevcallsolver(GEVDOORG_tgmsenvironment_OD_S*, void*, unsigned char const*, unsigned char const*, int, int, unsigned char const*, unsigned char const*, double, int, int, double, double, void**, unsigned char*) (gevdoorg.c:3427)
   by 0x5241786: gevcallsolver (joatdclib.c:5854)
 Address 0x5158ab0 is 0 bytes inside a block of size 31 free'd
   at 0x4839EAB: operator delete(void*) (vg_replace_malloc.c:586)
   by 0x5ABBBB2: SHOT::MIPSolverCbc::solveProblem() (MIPSolverCbc.cpp:390)
   by 0x5B2B2A1: SHOT::TaskSolveIteration::run() (TaskSolveIteration.cpp:128)
   by 0x5A9B9F1: SHOT::SolutionStrategyMultiTree::solveProblem() (SolutionStrategyMultiTree.cpp:305)
   by 0x5A3984A: SHOT::Solver::solveProblem() (Solver.cpp:552)
   by 0x5BA8564: shtCallSolver (EntryPointsGAMS.cpp:201)
   by 0x5BA8A63: C__shtCallSolver (EntryPointsGAMS.cpp:252)
   by 0x52AFFEE: GMSCONF_tgmsconf_DOT_sccallsolver(GMSCONF_tgmsconf_OD_S*, int, void*, void*) (gmsconf.c:2443)
   by 0x52A4B6D: libsolver(unsigned char*, unsigned char*, unsigned char const*, GMOMDODEFEX_tgmomodel_OD_S**, GEVDOORG_tgmsenvironment_OD_S**) (gevdoorg.c:3042)
   by 0x52A61A3: GEVDOORG_tgmsenvironment_DOT_gevcallsolver(GEVDOORG_tgmsenvironment_OD_S*, void*, unsigned char const*, unsigned char const*, int, int, unsigned char const*, unsigned char const*, double, int, int, double, double, void**, unsigned char*) (gevdoorg.c:3427)
   by 0x5241786: gevcallsolver (joatdclib.c:5854)
   by 0x11ECE9: GEVMDODEF_tgmsenvironment_DOT_gevcallsolver(GEVMDODEF_tgmsenvironment_OD_S*, void*, unsigned char const*, unsigned char const*, int, int, unsigned char const*, unsigned char const*, double, int, int, double, double, void**, unsigned char*) (gevmdodef.c:848)
 Block was alloc'd at
   at 0x4838DEF: operator new(unsigned long) (vg_replace_malloc.c:344)
   by 0x49D5631: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long) (basic_string.tcc:317)
   by 0x49D6581: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long) (basic_string.tcc:466)
   by 0x59D7489: std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) (basic_string.h:6111)
   by 0x5ABBB90: SHOT::MIPSolverCbc::solveProblem() (MIPSolverCbc.cpp:390)
   by 0x5B2B2A1: SHOT::TaskSolveIteration::run() (TaskSolveIteration.cpp:128)
   by 0x5A9B9F1: SHOT::SolutionStrategyMultiTree::solveProblem() (SolutionStrategyMultiTree.cpp:305)
   by 0x5A3984A: SHOT::Solver::solveProblem() (Solver.cpp:552)
   by 0x5BA8564: shtCallSolver (EntryPointsGAMS.cpp:201)
   by 0x5BA8A63: C__shtCallSolver (EntryPointsGAMS.cpp:252)
   by 0x52AFFEE: GMSCONF_tgmsconf_DOT_sccallsolver(GMSCONF_tgmsconf_OD_S*, int, void*, void*) (gmsconf.c:2443)
   by 0x52A4B6D: libsolver(unsigned char*, unsigned char*, unsigned char const*, GMOMDODEFEX_tgmomodel_OD_S**, GEVDOORG_tgmsenvironment_OD_S**) (gevdoorg.c:3042)

Invalid write of size 8
   at 0x6284FB7: ClpModel::emptyProblem(int*, double*, bool) (in )
   by 0x62E62A0: ClpSimplex::startup(int, int) (in )
   by 0x62F9690: ClpSimplexDual::startupSolve(int, double*, int) (in )
   by 0x62FBCDD: ClpSimplexDual::dual(int, int) (in )
   by 0x62D8BD8: ClpSimplex::dual(int, int) (in )
   by 0x633F07D: ClpSimplex::initialSolve(ClpSolve&) (in )
   by 0x624255C: OsiClpSolverInterface::initialSolve() (in )
   by 0x611B738: CbcModel::initialSolve() (in )
   by 0x604E93C: CbcMain1(int, char const**, CbcModel&, int (*)(CbcModel*, int), CbcSolverUsefulData&) (in )
   by 0x6079654: CbcMain1(int, char const**, CbcModel&) (in )
   by 0x5ABC446: SHOT::MIPSolverCbc::solveProblem() (MIPSolverCbc.cpp:440)
   by 0x5B2B2A1: SHOT::TaskSolveIteration::run() (TaskSolveIteration.cpp:128)
 Address 0x101f9be8 is 8 bytes before a block of size 32 alloc'd
   at 0x483950F: operator new[](unsigned long) (vg_replace_malloc.c:433)
   by 0x6284EF2: ClpModel::emptyProblem(int*, double*, bool) (in )
   by 0x62E62A0: ClpSimplex::startup(int, int) (in )
   by 0x62F9690: ClpSimplexDual::startupSolve(int, double*, int) (in )
   by 0x62FBCDD: ClpSimplexDual::dual(int, int) (in )
   by 0x62D8BD8: ClpSimplex::dual(int, int) (in )
   by 0x633F07D: ClpSimplex::initialSolve(ClpSolve&) (in )
   by 0x624255C: OsiClpSolverInterface::initialSolve() (in )
   by 0x611B738: CbcModel::initialSolve() (in )
   by 0x604E93C: CbcMain1(int, char const**, CbcModel&, int (*)(CbcModel*, int), CbcSolverUsefulData&) (in )
   by 0x6079654: CbcMain1(int, char const**, CbcModel&) (in )
   by 0x5ABC446: SHOT::MIPSolverCbc::solveProblem() (MIPSolverCbc.cpp:440)
```
Let me know if you cannot reproduce and I'll dig deeper.

**Comment by andreaslundell** [comment]
@svigerske This seems to have been fixed in the nonconvex branch because I can solve the problem using that. Can you confirm? 

That branch contains a lot of fixes that have not yet been merged into the main one yet (I will soon).

**Comment by svigerske** [comment]
No, I still get the same. I'll need to look closer then.
The invalid reads are easy to fix are a problem in the SHOT code. You do something like
```
    argv[4] = ("-nodestrategy=" + env->settings->getSetting<std::string>("Cbc.NodeStrategy", "Subsolver")).c_str();
```
But the char* returned there does not live long, as the std::string is just temporary.
Putting a strdup() around fixes this, though one should free this mem again somewhere.

But the invalid write deep within Clp remains.

**Comment by andreaslundell** [comment]
Using the nonconvex branch, does SHOT still say that the reformulated problem is MIQP? As in the latter of:
`Problem classification:     MIQP, convex         MIQP, convex`

SHOT should figure out that Cbc does not support MIQP problems and consider it as an MINLP...

**Comment by svigerske** [comment]
It still claims MIQP:
```
╶ Problem instance ───────────────────────────────────────────────────────────────────────────────────────────────────╴

                                    Original             Reformulated

 Problem classification:            MIQP, convex         MIQP, convex

 Objective function direction:      minimize             minimize
 Objective function type:           quadratic, convex    quadratic, convex

 Number of constraints:             3                    3
  - linear:                         3                    3

 Number of variables:               4                    4
  - real:                           2                    2
  - binary:                         2                    2
  - nonlinear:                      2                    2
```

**Comment by andreaslundell** [comment]
Ok, strange, I assume it doesn't do this when running SHOT directly on the problem? I have not tried calling SHOT from GAMS in a while, but I will set it up and see what I find. But it will have to wait until tomorrow unfortunately.

**Comment by svigerske** [comment]
Indeed, it's different when I run on a osil file.
It seems that `Solver::setProblem(SHOT::ProblemPtr problem, SHOT::ModelingSystemPtr modelingSystem)` and `Solver::setProblem(std::string fileName)` were out of sync. I can even fix this.
But it shouldn't have crashed anyway :).
